### ISSUE TITLE
Android project needs to be rebuilt after every change in a Spek scope

### ISSUE THREAD

**Issue by Adambl4** [raniejade/spek-idea-plugin#6]
Otherwise plugin doesn't catch that changes
AS      `2.1.3`
Plugin `0.2.4`

```
 testCompile 'org.jetbrains.spek:spek-api:1.0.89'
 testCompile 'org.jetbrains.spek:spek-junit-platform-engine:1.0.89'
 testCompile "org.junit.platform:junit-platform-runner:1.0.0-M2"
```

**Comment by raniejade** [comment]
Still setting up an android dev environment, but I got a question. In the run/debug configuration do you have something like this (Before launcher: Make, ...:)?

![screenshot from 2016-09-03 11 33 14](https://cloud.githubusercontent.com/assets/1041919/18222442/6e73c6c4-71ca-11e6-848b-e5983bb42a3e.png)

**Comment by raniejade** [comment]
Okay I know the problem, it's the 'Make'. Looking at a JUnit run configuration:

![screenshot from 2016-09-03 13 17 10](https://cloud.githubusercontent.com/assets/1041919/18222926/da09952c-71d8-11e6-8270-6a2a18b79a25.png)

It has a `Gradle-aware make` which is not available for Spek's run configuration. See https://android.googlesource.com/platform/tools/adt/idea/+/studio-master-dev/android/src/com/android/tools/idea/gradle/run/MakeBeforeRunTaskProvider.java

As a workaround, remove the `Make` before launch step and add a gradle step that will run  `assembleDebugUnitTest` task.

**Comment by raniejade** [comment]
For reference: https://youtrack.jetbrains.com/issue/IDEA-131627

**Comment by raniejade** [comment]
https://code.google.com/p/android/issues/detail?id=233597

**Comment by raniejade** [comment]
Should be fixed in `v0.4.1`.

**Comment by patjackson52** [comment]
Still seeing this bug with AS 3.0.1 & spek plugin v0.5.4-studio3.0.  A build must be completed before running the spek test for it to use the updated code in the tests.

**Comment by raniejade** [comment]
@patjackson52 That's weird, can you check if you have `Gradle-aware Make` in the created run configuration?

**Comment by patjackson52** [comment]
Yes, it was there by default.  I removed it and added a gradle task for assemble (This is not an Android module, so I do not have assembleDebugUnitTest).  I then get this error:

WARNING: TestEngine with ID 'spek' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: MaestroSpec
	at org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:71)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:70)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:79)

**Comment by raniejade** [comment]
Have you tried running it w/ `Gradle-aware Make`? It should handle cases for non android modules.

**Comment by patjackson52** [comment]
Yes, when running w/ `Gradle-aware Make` it does not use updated code, and I have to build it separately before running the Spek tests.

**Comment by raniejade** [comment]
Hmm, can you try our test sample project https://github.com/spekframework/spek-android-example? It also includes a non-android module.

**Comment by patjackson52** [comment]
Ok, Sample project works fine.  I found more info on why this is not working for me.

My project does not have any android modules.  I tested the sample project by removing the android module and the behavior was the same, it ran the test but did not use updated code.

It would be great if Spek could support projects w/o android modules in AS.  I understand this is ANDROID Studio, and there is Intellij CE which runs Spek just fine.  My case is probably not a common one, but I need AS.  Any ideas if this is an easy fix?  I may be able to contribute if you point me in the right direction.

**Comment by patjackson52** [comment]
Intellij using the run config "Spek - JVM" where android uses the config "Spek - Android".  Is there a way to use "Spek - JVM" in AS?

**Comment by raniejade** [comment]
@patjackson52 I tried implementing that initially, but it's really hard to implement correctly. The AS 3.0 support is already hacky, I don't want to add more to that mess. Why do you need AS for that?

**Comment by patjackson52** [comment]
It's kind of a long story.  Basically I have an AppEngine project and
running local builds with debugging works much better with the AS +
plugin.  Hoping there was a easy fix, but if not this is proy not worth
it.  That and keeping g the same IDE for Android and non Android projects.
